name: CI

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up cargo-ndk
        run: cargo install cargo-ndk

      - name: set up aarch64 target
        run: rustup target add aarch64-linux-android

      - name: build
        run: cargo ndk --target aarch64-linux-android build --release

      - name: move files
        run: |
          mv target/aarch64-linux-android/release/linjector-cli ./linjector-cli

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./linjector-cli
